---
- hosts: all
  become: true
  vars:
    hostname: "R1"
    enable_secret: "class"
    console_password: = "cisco"
    vty_password: = "cisco"

  tasks:

  - name: Enable
    ios_config:
      lines: ['enable']

  - name: Configure terminal
    ios_config:
      commands: ['configure terminal']

  - name: Set hostname
    ios_config:
      commands: ['hostname {{ hostname }}']

  - name: Set enable secret
    ios_config:
      commands: ['enable secret {{ enable_secret }}']

  - name: Encrypt service password
    ios_config:
      commands: ['service password-encryption']

  - name: Set banner message
    ios_config:
      commands: ['banner motd "Unauthorized Person Only"']

  - name: Configure console line
    ios_config:
      commands:
        - 'line console 0'
        - 'password {{ console_password }}'
        - 'login'
        - 'exit'

  - name: Configure VTY lines
    ios_config:
      commands:
        - 'line vty 0 15'
        - 'password {{ console_password }}'
        - 'login'
        - 'exit'

  - name: Save config
    ios_config:
      commands: ['do show running-config', 'do copy running-config startup-config']
